include: package:pedantic/analysis_options.yaml
analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: true

  language:
    strict-inference: true
    strict-raw-types: true

  errors:
    always_declare_return_types: error
    always_require_non_null_named_parameters: error
    annotate_overrides: error
    avoid_catches_without_on_clauses: error
    avoid_catching_errors: error
    avoid_equals_and_hash_code_on_mutable_classes: error
    avoid_renaming_method_parameters: error
    avoid_returning_null: error
    avoid_returning_null_for_future: error
    avoid_returning_null_for_void: error
    avoid_shadowing_type_parameters: error
    avoid_types_as_parameter_names: error
    avoid_void_async: error
    avoid_web_libraries_in_flutter: error
    await_only_futures: error
    camel_case_extensions: error
    camel_case_types: error
    can_be_null_after_null_aware: error
    comment_references: warning
    constant_identifier_names: error
    control_flow_in_finally: error
    curly_braces_in_flow_control_structures: error
    equal_elements_in_set: error
    equal_keys_in_map: error
    exhaustive_cases: error
    file_names: error
    implementation_imports: error
    include_file_not_found: error
    inference_failure_on_collection_literal: error
    inference_failure_on_function_return_type: error
    inference_failure_on_instance_creation: error
    inference_failure_on_uninitialized_variable: error
    inference_failure_on_untyped_parameter: error
    invalid_factory_annotation: error
    invalid_factory_method_impl: error
    invalid_literal_annotation: error
    invalid_override_different_default_values_named: error
    invalid_override_of_non_virtual_member: error
    invalid_required_named_param: error
    invalid_required_optional_positional_param: error
    invalid_required_positional_param: error
    invalid_use_of_protected_member: error
    invalid_use_of_visible_for_testing_member: error
    iterable_contains_unrelated_type: error
    library_names: error
    library_prefixes: error
    list_remove_unrelated_type: error
    missing_enum_constant_in_switch: error
    missing_required_param: error
    missing_return: error
    must_be_immutable: error
    must_call_super: error
    no_adjacent_strings_in_list: error
    no_duplicate_case_values: error
    no_logic_in_create_state: error
    non_const_call_to_literal_constructor: error
    non_constant_identifier_names: error
    null_aware_in_condition: error
    null_aware_in_logical_operator: error
    null_closures: error
    only_throw_errors: error
    overridden_fields: error
    override_on_non_overriding_member: error
    package_names: error
    package_prefixed_library_names: error
    parameter_assignments: error
    prefer_equal_for_default_values: error
    prefer_generic_function_type_aliases: error
    prefer_mixin: error
    prefer_typing_uninitialized_variables: error
    prefer_void_to_null: error
    recursive_getters: error
    strict_raw_type: error
    test_types_in_equals: error
    throw_in_finally: error
    unawaited_futures: error
    undefined_hidden_name: error
    undefined_shown_name: error
    unnecessary_await_in_return: error
    unrelated_type_equality_checks: error
    unsafe_html: warning
    unsupported_option_with_legal_values: error
    use_full_hex_values_for_flutter_colors: error
    use_function_type_syntax_for_parameters: error
    valid_regexps: error
    void_checks: error

linter:
  rules:
    #- lines_longer_than_80_chars
    - always_declare_return_types
    #- always_put_control_body_on_new_line
    #- always_put_required_named_parameters_first
    - always_require_non_null_named_parameters
    - annotate_overrides
    - avoid_bool_literals_in_conditional_expressions
    - avoid_double_and_int_checks
    - avoid_empty_else
    - avoid_field_initializers_in_const_classes
    - avoid_init_to_null
    - avoid_null_checks_in_equality_operators
    - avoid_positional_boolean_parameters
    - avoid_relative_lib_imports
    - avoid_renaming_method_parameters
    - avoid_return_types_on_setters
    - avoid_returning_null
    - avoid_single_cascade_in_expression_statements
    - avoid_slow_async_io
    - avoid_types_as_parameter_names
    - avoid_unused_constructor_parameters
    - await_only_futures
    - camel_case_types
    - cancel_subscriptions
    - close_sinks
    - comment_references
    - constant_identifier_names
    - control_flow_in_finally
    - directives_ordering
    - empty_catches
    - empty_constructor_bodies
    - empty_statements
    - hash_and_equals
    - implementation_imports
    - invariant_booleans
    - iterable_contains_unrelated_type
    - join_return_with_assignment
    - library_names
    - library_prefixes
    - list_remove_unrelated_type
    - literal_only_boolean_expressions
    - no_duplicate_case_values
    - non_constant_identifier_names
    - null_closures
    - package_api_docs
    - package_names
    - package_prefixed_library_names
    - parameter_assignments
    - prefer_adjacent_string_concatenation
    - prefer_asserts_in_initializer_lists
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_constructors_over_static_methods
    - prefer_contains
    - prefer_equal_for_default_values
    - prefer_final_fields
    - prefer_final_locals
    - prefer_foreach
    - prefer_generic_function_type_aliases
    - prefer_interpolation_to_compose_strings
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_iterable_whereType
    - prefer_typing_uninitialized_variables
    - recursive_getters
    - slash_for_doc_comments
    - sort_constructors_first
    - sort_unnamed_constructors_first
    #- super_goes_last
    - test_types_in_equals
    - throw_in_finally
    - type_annotate_public_apis
    - type_init_formals
    - unawaited_futures
    - unnecessary_const
    - unnecessary_getters_setters
    - unnecessary_lambdas
    - unnecessary_new
    - unnecessary_null_aware_assignments
    - unnecessary_null_in_if_null_operators
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_statements
    - unnecessary_this
    - unrelated_type_equality_checks
    - use_rethrow_when_possible
    - use_string_buffers
    - use_to_and_as_if_applicable
    - valid_regexps
    - void_checks